name: Bash matrix

on:
  push:
  workflow_dispatch: {}

permissions: {}

jobs:
  greet:
    name: Print workspace path
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        name: [Alice, bob]

    steps:
      - name: Print greeting
        run: echo "Hello, ${{ matrix.name }}"
